version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - clientes-compose-network
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollclin_db

volumes:
  dbdata:

networks:
  clientes-compose-network:
    driver: bridge